services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_fiber_app
    ports:
      - "3002:3002"
    environment:
      - DB_USER=user
      - DB_PASSWORD=root
      - DB_NAME=stockAgg
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=XgC7LztJc5FlTyraJwhaKYVeH4vUNrcnoUsH1hPr3JM=
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stockAgg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "stockAgg"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 10s

volumes:
  postgres_data: {}
